### ISSUE TITLE
Php variable color

### ISSUE THREAD

**Issue by szekelygobe** [gerardroche/sublime-monokai-free#2]
Hi! 
I'm using your Color Scheme with PHP programing. 
I'd like to change the color of the variables $foo from white to sometning else.
How can I do that ?
Thank you.

**Comment by szekelygobe** [comment]
Using https://github.com/bobef/ColorSchemeEditor I did change the colors.
Thank you!

**Comment by gerardroche** [comment]
In the newest builds of ST you can take advantage of the new color scheme format to customise things.

For completness (without the need for a plugin):

Create a file in your user directory `User/MonokaiFree.sublime-color-scheme` and then customise as you please:

To make the `$` yellow and the variable name green for in example: `$variable`:
 
```
{
    "rules":
    [
        {
            "scope": "variable.other.php punctuation.definition.variable.php",
            "foreground": "#ffff00"
        },
        {
            "scope": "variable.other.php",
            "foreground": "#00ff00"
        }
    ]
}
```


Change the background and comments:

```
{
    "globals":
    {
        "background": "#1b1d1e",
        "gutter": "#1b1d1e"
    },
    "rules":
    [
        {
            "scope": "comment, punctuation.definition.comment",
            "foreground": "#7e8e91"
        }
    ]
}
```

**Comment by szekelygobe** [comment]
Ok, thank you for the advice.
