### ISSUE TITLE
Add MonokaiFree UI theme

### ISSUE THREAD

**Issue by barnumbirr** [gerardroche/sublime-monokai-free#5]
Hey there,  
would it be possible to add a `MonokaiFree` UI theme? I'm coming from `Boxy Monokai`, which is unfortunately one of the packages that suddenly disappears, and would love to switch to a full `MonokaiFree` setup. 
Cheers.

**Comment by gerardroche** [comment]
I use the default Adaptive theme, so I wouldn't be motivated to learn how to do a UI theme and maintain it. If I did one I think I would still prefer it to be a separate package though.

**Comment by gerardroche** [comment]
I added some enhancements to the adaptive theme.


## Theme

Menu → Preferences → Select Theme → Adaptive

**Enable enhancements**

Menu → Preferences → Settings

```js
"monokaifree.theme": true,
```

**Configurations**

Menu → Preferences → Settings

```js
"monokaifree.vcs_status_labels": true,
"monokaifree.vcs_status_badges": true,
```
